version: "3.9"
name: {{project-name}}

services:
  {{project-name}}:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: {{project-name}}
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ../:/app
      - target:/app/target
      - cargo:/usr/local/cargo/registry
    environment:
      DATABASE_URL: "postgres://postgres:postgres@{{project-name}}-db:5432/{{project-name | snake_case}}_db"
    depends_on:
      - {{project-name}}-db
    command: cargo watch -x run

  {{project-name}}-db:
    image: postgres:17-alpine
    container_name: {{project-name}}-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{project-name | snake_case}}_db
    ports:
      - "5432:5432"
    volumes:
      - {{project-name}}_db_data:/var/lib/postgresql/data

volumes:
  target:
  cargo:
  {{project-name}}_db_data:
